name: segit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3
  flutter_image_slideshow: ^0.1.6
  iconly: ^1.0.1
  url_launcher: ^6.2.4
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  vibration: ^1.8.4
  pull_to_refresh: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

